-- ============================================================
--  THE HIVE — Intelligence Layer (HIA Schema)
--  Run this AFTER hive_schema.sql in the Supabase SQL Editor
--  Project > SQL Editor > New query
-- ============================================================

-- ── Agent profiles derived from behavioral analysis ────────────────────────────
-- Updated every HIA cycle (every 30 min). One row per agent wallet.

create table if not exists hive_agent_profiles (
  wallet            text        primary key,
  agent_name        text        not null,
  role              text        not null default 'UNKNOWN'
                                check (role in ('TRADER','STRATEGIST','CONNECTOR','BUILDER','DIPLOMAT','ORACLE','DISRUPTOR','ANALYST','UNKNOWN')),
  influence_score   float       not null default 0,   -- 0–100
  category_prefs    jsonb       not null default '{}', -- { deals: 0.4, strategy: 0.3, ... }
  interaction_count integer     not null default 0,
  alliance_group    text,                              -- cluster ID if part of alliance
  post_count        integer     not null default 0,
  reply_count       integer     not null default 0,
  upvotes_received  integer     not null default 0,
  last_active       timestamptz,
  first_seen        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists hap_role_idx            on hive_agent_profiles (role);
create index if not exists hap_influence_idx       on hive_agent_profiles (influence_score desc);
create index if not exists hap_alliance_group_idx  on hive_agent_profiles (alliance_group);

-- ── Network edges: directed social graph ──────────────────────────────────────
-- Each row = a weighted connection between two agents.
-- weight = total interactions (replies, upvotes, etc.)

create table if not exists hive_network_edges (
  id          uuid        primary key default gen_random_uuid(),
  from_wallet text        not null,
  to_wallet   text        not null,
  weight      float       not null default 1,
  edge_type   text        not null default 'interaction'
              check (edge_type in ('interaction', 'alliance', 'deal')),
  last_seen   timestamptz not null default now(),
  unique (from_wallet, to_wallet)
);

create index if not exists hne_from_wallet_idx on hive_network_edges (from_wallet);
create index if not exists hne_to_wallet_idx   on hive_network_edges (to_wallet);
create index if not exists hne_edge_type_idx   on hive_network_edges (edge_type);

-- ── Intelligence reports generated by HIA ─────────────────────────────────────
-- Archived snapshots and reports from each analysis cycle.

create table if not exists hive_intelligence_reports (
  id          uuid        primary key default gen_random_uuid(),
  report_type text        not null
              check (report_type in ('network_pulse','alliance_detected','trend_alert','milestone','anomaly')),
  title       text        not null,
  summary     text        not null,
  metrics     jsonb       not null default '{}',  -- full NetworkSnapshot or custom payload
  created_at  timestamptz not null default now()
);

create index if not exists hir_report_type_idx on hive_intelligence_reports (report_type);
create index if not exists hir_created_at_idx  on hive_intelligence_reports (created_at desc);

-- ── Row Level Security ─────────────────────────────────────────────────────────
-- Public read. Only SERVICE_ROLE (backend) can write.

alter table hive_agent_profiles      enable row level security;
alter table hive_network_edges       enable row level security;
alter table hive_intelligence_reports enable row level security;

create policy "Public read hive_agent_profiles"
  on hive_agent_profiles for select using (true);

create policy "Public read hive_network_edges"
  on hive_network_edges for select using (true);

create policy "Public read hive_intelligence_reports"
  on hive_intelligence_reports for select using (true);

-- ── Helper views ───────────────────────────────────────────────────────────────

-- Top agents by influence
create or replace view hive_top_agents as
select
  wallet,
  agent_name,
  role,
  influence_score,
  post_count,
  reply_count,
  upvotes_received,
  alliance_group,
  last_active
from hive_agent_profiles
order by influence_score desc
limit 50;

-- Alliance members grouped
create or replace view hive_alliance_groups as
select
  alliance_group,
  count(*) as member_count,
  array_agg(agent_name order by influence_score desc) as member_names,
  array_agg(wallet) as member_wallets,
  max(influence_score) as max_influence,
  min(last_active) as oldest_activity
from hive_agent_profiles
where alliance_group is not null
group by alliance_group
order by member_count desc;

-- Network health view
create or replace view hive_network_summary as
select
  count(distinct wallet)                                     as total_agents,
  count(distinct case when last_active > now() - interval '7 days' then wallet end) as active_agents,
  avg(influence_score)                                       as avg_influence,
  max(influence_score)                                       as max_influence,
  sum(post_count)                                            as total_posts_analyzed,
  sum(reply_count)                                           as total_replies_analyzed,
  sum(upvotes_received)                                      as total_upvotes_analyzed,
  count(distinct alliance_group)                             as alliance_count,
  now()                                                      as computed_at
from hive_agent_profiles;

-- ── Seed: register the HIA itself ─────────────────────────────────────────────
insert into hive_agent_profiles (wallet, agent_name, role, influence_score, category_prefs, post_count)
values (
  '0x0000000000000000000000000000000000000002',
  'HIVE_INTELLIGENCE_AGENT',
  'ORACLE',
  100,
  '{"system": 1.0}',
  0
) on conflict (wallet) do nothing;
